import path from 'node:path'

import { Inject, Injectable, Logger } from '@nestjs/common'

import { FileSystem } from '@/helpers/fs.js'
import type { KnowledgeInsight } from '@/modules/context/context.types.js'
import type { KnowledgeCategory } from '@/modules/context/context.types.js'
import { KNOWLEDGE_CATEGORY_LABELS } from '@/modules/context/context.types.js'
import { StateService } from '@/modules/state/state.service.js'

const KNOWLEDGE_HEADER =
  '> Auto-generated by 2context. Edit freely — new runs append, never overwrite existing content.\n'
const SECTION_SEPARATOR = '\n---\n'

@Injectable()
export class WriterService {
  private readonly logger = new Logger('WriterService')

  constructor(@Inject(StateService) private readonly stateService: StateService) {}

  /**
   * Write all knowledge insights to their appropriate locations.
   * Returns a list of relative file paths that were written or updated.
   */
  public async writeInsights(insights: KnowledgeInsight[], repoRoot: string): Promise<string[]> {
    const fs = new FileSystem(repoRoot)
    const writtenFiles: string[] = []

    await this.stateService.ensureKnowledgeDirs()

    // Group insights by their target file
    const fileInsights = this.groupInsightsByFile(insights, repoRoot)

    for (const [filePath, fileInsightList] of fileInsights) {
      await this.writeKnowledgeFile(fs, filePath, fileInsightList, repoRoot)
      writtenFiles.push(path.relative(repoRoot, filePath))
    }

    // Write knowledge index
    const indexPath = await this.writeKnowledgeIndex(fs, insights)
    writtenFiles.push(path.relative(repoRoot, indexPath))

    this.logger.log(`Wrote ${writtenFiles.length} knowledge files`)
    return writtenFiles
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  private groupInsightsByFile(insights: KnowledgeInsight[], repoRoot: string): Map<string, KnowledgeInsight[]> {
    const groups = new Map<string, KnowledgeInsight[]>()

    for (const insight of insights) {
      const filePath = this.resolveInsightPath(insight, repoRoot)
      const existing = groups.get(filePath) || []
      existing.push(insight)
      groups.set(filePath, existing)
    }

    return groups
  }

  private resolveInsightPath(insight: KnowledgeInsight, repoRoot: string): string {
    const scope = insight.scope

    if (scope.type === 'file') {
      const dir = path.dirname(path.join(repoRoot, scope.filePath))
      return path.join(dir, 'KNOWLEDGE.md')
    }

    if (scope.type === 'folder') {
      return path.join(repoRoot, scope.folderPath, 'KNOWLEDGE.md')
    }

    // General → .2context/knowledge/{category}/{slug}.md
    const knowledgeDir = this.stateService.getKnowledgeDir()
    const slug = this.slugify(insight.title)
    return path.join(knowledgeDir, insight.category, `${slug}.md`)
  }

  private async writeKnowledgeFile(
    fs: FileSystem,
    filePath: string,
    insights: KnowledgeInsight[],
    repoRoot: string,
  ): Promise<void> {
    const stateDir = this.stateService.getStateDir()
    const isInSourceTree = !filePath.startsWith(stateDir)

    if (isInSourceTree) {
      await this.appendToKnowledgeFile(fs, filePath, insights, repoRoot)
    } else {
      // General knowledge files — one file per insight
      await this.writeGeneralKnowledgeFile(fs, filePath, insights[0])
    }
  }

  /**
   * Append new insights to an existing KNOWLEDGE.md, skipping duplicates by title.
   */
  private async appendToKnowledgeFile(
    fs: FileSystem,
    filePath: string,
    insights: KnowledgeInsight[],
    repoRoot: string,
  ): Promise<void> {
    const existingContent = (await fs.readFileOrNull(filePath)) || ''

    const existingTitles = this.extractExistingTitles(existingContent)
    const newInsights = insights.filter((i) => !existingTitles.has(i.title))

    if (newInsights.length === 0) {
      this.logger.log(`Skipping ${filePath} — all insights already present`)
      return
    }

    let content = existingContent

    if (!content) {
      const relativePath = path.relative(repoRoot, path.dirname(filePath))
      content = `# Knowledge — ${relativePath || 'root'}\n\n${KNOWLEDGE_HEADER}\n`
    }

    for (const insight of newInsights) {
      content += SECTION_SEPARATOR
      content += this.formatInsightSection(insight)
    }

    await fs.writeFileWithDir(filePath, content)
  }

  private async writeGeneralKnowledgeFile(fs: FileSystem, filePath: string, insight: KnowledgeInsight): Promise<void> {
    const content =
      `# ${insight.title}\n\n` +
      `**Category:** ${KNOWLEDGE_CATEGORY_LABELS[insight.category]}\n` +
      `**Source commits:** ${insight.sourceCommits.join(', ')}\n\n` +
      `${insight.content}\n`

    await fs.writeFileWithDir(filePath, content)
  }

  private formatInsightSection(insight: KnowledgeInsight): string {
    return (
      `\n## ${insight.title}\n\n` +
      `**Category:** ${KNOWLEDGE_CATEGORY_LABELS[insight.category]}\n` +
      `**Source commits:** ${insight.sourceCommits.join(', ')}\n\n` +
      `${insight.content}\n`
    )
  }

  private async writeKnowledgeIndex(fs: FileSystem, insights: KnowledgeInsight[]): Promise<string> {
    const knowledgeDir = this.stateService.getKnowledgeDir()
    const indexPath = path.join(knowledgeDir, 'index.md')

    let content = '# Knowledge Index\n\n'
    content += `Generated: ${new Date().toISOString()}\n\n`

    const byCategory = new Map<KnowledgeCategory, KnowledgeInsight[]>()
    for (const insight of insights) {
      const list = byCategory.get(insight.category) || []
      list.push(insight)
      byCategory.set(insight.category, list)
    }

    for (const [category, categoryInsights] of byCategory) {
      content += `## ${KNOWLEDGE_CATEGORY_LABELS[category]}\n\n`

      for (const insight of categoryInsights) {
        const scope = insight.scope
        if (scope.type === 'general') {
          const slug = this.slugify(insight.title)
          content += `- [${insight.title}](./${category}/${slug}.md)\n`
        } else {
          const locationPath = scope.type === 'file' ? path.dirname(scope.filePath) : scope.folderPath
          content += `- ${insight.title} → \`${locationPath}/KNOWLEDGE.md\`\n`
        }
      }

      content += '\n'
    }

    await fs.ensureDir(knowledgeDir)
    await fs.writeFileWithDir(indexPath, content)

    return indexPath
  }

  private extractExistingTitles(content: string): Set<string> {
    const titles = new Set<string>()
    const regex = /^## (.+)$/gm
    let match

    while ((match = regex.exec(content)) !== null) {
      titles.add(match[1])
    }

    return titles
  }

  private slugify(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .substring(0, 60)
  }
}
