import fs from 'node:fs/promises'
import path from 'node:path'

import { Injectable, Logger } from '@nestjs/common'

import { FileSystem } from '@/helpers/fs.js'
import type { KnowledgeItem } from '@/modules/adapters/adapter.types.js'
import { KNOWLEDGE_CATEGORY_LABELS } from '@/modules/adapters/adapter.types.js'

const CO_LOCATED_HEADER =
  '> Auto-generated by 2context. Edit freely — new runs append, never overwrite existing content.\n'
const SECTION_SEPARATOR = '\n---\n'

/**
 * Writes knowledge items to disk. Two output planes:
 *   1. Co-located `KNOWLEDGE.md` files next to the source code they describe.
 *   2. Central `.2context/graph/{category}[/{subcategoryPath…}]/{slug}.md` files.
 *
 * The writer is driven entirely by the `writtenPath` field on each item —
 * callers (the pipeline, rebalance) are responsible for computing that path.
 */
@Injectable()
export class WriterService {
  private readonly logger = new Logger('WriterService')

  /**
   * Write a batch of newly-produced items. Co-located items are appended to
   * their host files (skipping titles that already exist). General-scope
   * items are written as new files.
   */
  public async writeNewItems(items: KnowledgeItem[], repoRoot: string): Promise<void> {
    const filesystem = new FileSystem(repoRoot)

    // Group by their host KNOWLEDGE.md for co-located items so we only
    // touch each file once per run.
    const coLocatedByFile = new Map<string, KnowledgeItem[]>()
    const generalItems: KnowledgeItem[] = []

    for (const item of items) {
      if (item.scope.type === 'general') {
        generalItems.push(item)
      } else {
        const existing = coLocatedByFile.get(item.writtenPath) ?? []
        existing.push(item)
        coLocatedByFile.set(item.writtenPath, existing)
      }
    }

    for (const [hostPath, hostItems] of coLocatedByFile) {
      await this.appendCoLocated(filesystem, hostPath, hostItems, repoRoot)
    }

    for (const item of generalItems) {
      await this.writeCentralItem(repoRoot, item)
    }
  }

  /**
   * Remove an item from its current hosting file. Used by `validate` and by
   * `rebalance` when moving an item (remove from old location, then write at new).
   */
  public async removeItem(item: KnowledgeItem, repoRoot: string): Promise<void> {
    if (item.scope.type === 'general') {
      const abs = path.join(repoRoot, item.writtenPath)
      await this.unlinkIfExists(abs)
      return
    }

    // Co-located: rewrite the KNOWLEDGE.md file without this item.
    const filesystem = new FileSystem(repoRoot)
    await this.rewriteCoLocatedExcluding(filesystem, item.writtenPath, item.title, repoRoot)
  }

  /**
   * Write (or rewrite) a single central graph item file based on current state.
   * Used by rebalance after moving files.
   */
  public async writeCentralItem(repoRoot: string, item: KnowledgeItem): Promise<void> {
    if (item.scope.type !== 'general') return

    const filesystem = new FileSystem(repoRoot)
    const content = this.formatCentralItem(item)
    await filesystem.writeFileWithDir(item.writtenPath, content)
  }

  /**
   * Rebuild a co-located KNOWLEDGE.md from the set of items currently assigned
   * to it in state. Used by `validate` and any code path that mutates the
   * in-file item set.
   */
  public async rewriteCoLocatedFromItems(repoRoot: string, hostPath: string, items: KnowledgeItem[]): Promise<void> {
    const filesystem = new FileSystem(repoRoot)

    if (items.length === 0) {
      await this.unlinkIfExists(path.join(repoRoot, hostPath))
      return
    }

    const relativeDir = path.relative(repoRoot, path.dirname(path.join(repoRoot, hostPath))) || 'root'
    let content = `# Knowledge — ${relativeDir}\n\n${CO_LOCATED_HEADER}`

    for (const item of items) {
      content += SECTION_SEPARATOR
      content += this.formatCoLocatedSection(item)
    }

    await filesystem.writeFileWithDir(hostPath, content)
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  private async appendCoLocated(
    filesystem: FileSystem,
    hostPath: string,
    items: KnowledgeItem[],
    repoRoot: string,
  ): Promise<void> {
    const existing = (await filesystem.readFileOrNull(hostPath)) || ''
    const existingTitles = this.extractExistingTitles(existing)
    const newItems = items.filter((i) => !existingTitles.has(i.title))

    if (newItems.length === 0) {
      this.logger.log(`Skipping ${hostPath} — all items already present`)
      return
    }

    let content = existing
    if (!content) {
      const relativeDir = path.relative(repoRoot, path.dirname(path.join(repoRoot, hostPath))) || 'root'
      content = `# Knowledge — ${relativeDir}\n\n${CO_LOCATED_HEADER}`
    }

    for (const item of newItems) {
      content += SECTION_SEPARATOR
      content += this.formatCoLocatedSection(item)
    }

    await filesystem.writeFileWithDir(hostPath, content)
  }

  private async rewriteCoLocatedExcluding(
    filesystem: FileSystem,
    hostPath: string,
    excludeTitle: string,
    _repoRoot: string,
  ): Promise<void> {
    const existing = await filesystem.readFileOrNull(hostPath)
    if (!existing) return

    // Split into head (before first item heading) + sections
    const lines = existing.split('\n')
    const sections: { title: string; content: string }[] = []
    const head: string[] = []
    let currentSection: { title: string; content: string } | null = null

    for (const line of lines) {
      const headingMatch = /^## (.+)$/.exec(line)
      if (headingMatch) {
        if (currentSection) sections.push(currentSection)
        currentSection = { title: headingMatch[1], content: `${line}\n` }
      } else if (currentSection) {
        currentSection.content += `${line}\n`
      } else {
        head.push(line)
      }
    }

    if (currentSection) sections.push(currentSection)

    const kept = sections.filter((s) => s.title !== excludeTitle)

    if (kept.length === 0) {
      await this.unlinkIfExists(filesystem.resolve(hostPath))
      return
    }

    // Strip trailing separator from each section's content, re-join with separators
    const body = kept.map((s) => s.content.replace(/\n---\n\s*$/, '').trimEnd()).join('\n\n---\n\n')

    const rebuilt = head.join('\n').trimEnd() + '\n\n' + body + '\n'
    await filesystem.writeFileWithDir(hostPath, rebuilt)
  }

  private formatCentralItem(item: KnowledgeItem): string {
    const categoryLine = this.formatCategoryPath(item)
    const sourcesLine = item.sources.join(', ') || '—'
    const relatedLine = item.relatedFiles.length > 0 ? item.relatedFiles.join(', ') : null

    let out = `# ${item.title}\n\n`
    out += `**Category:** ${categoryLine}\n`
    out += `**Summary:** ${item.summary}\n`
    out += `**Sources:** ${sourcesLine}\n`
    if (relatedLine) out += `**Related files:** ${relatedLine}\n`
    out += `\n${item.content.trim()}\n`
    return out
  }

  private formatCoLocatedSection(item: KnowledgeItem): string {
    const sourcesLine = item.sources.join(', ') || '—'

    let out = `\n## ${item.title}\n\n`
    out += `**Category:** ${KNOWLEDGE_CATEGORY_LABELS[item.category]}\n`
    out += `**Summary:** ${item.summary}\n`
    out += `**Sources:** ${sourcesLine}\n\n`
    out += `${item.content.trim()}\n`
    return out
  }

  private formatCategoryPath(item: KnowledgeItem): string {
    const root = KNOWLEDGE_CATEGORY_LABELS[item.category]
    if (item.subcategoryPath.length === 0) return root
    return [root, ...item.subcategoryPath].join(' / ')
  }

  private extractExistingTitles(content: string): Set<string> {
    const titles = new Set<string>()
    const regex = /^## (.+)$/gm
    let match: RegExpExecArray | null

    while ((match = regex.exec(content)) !== null) {
      titles.add(match[1])
    }

    return titles
  }

  private async unlinkIfExists(absPath: string): Promise<void> {
    try {
      await fs.unlink(absPath)
    } catch {
      // Missing file is fine
    }
  }
}
