import fs from 'node:fs/promises'
import path from 'node:path'

import { Injectable, Logger } from '@nestjs/common'

import { FileSystem } from '@/helpers/fs.js'
import type { KnowledgeItem } from '@/modules/adapters/adapter.types.js'
import { KNOWLEDGE_CATEGORY_LABELS } from '@/modules/adapters/adapter.types.js'
import type { GraphNode } from '@/modules/state/state.types.js'

const CO_LOCATED_HEADER =
  '> Auto-generated by 2context. Edit freely — new runs append, never overwrite existing content.\n'
const SECTION_SEPARATOR = '\n---\n'

/**
 * File-IO layer for the knowledge graph. Two output planes:
 *   1. Co-located `KNOWLEDGE.md` files next to source code (file/folder scope).
 *   2. Tree of leaves and `_index.md` files under `.2context/graph/` (general scope).
 *
 * The IndexService owns the tree shape and decides what to render where; this
 * service only knows how to produce the markdown for one node at a time.
 */
@Injectable()
export class WriterService {
  private readonly logger = new Logger('WriterService')

  // ── Co-located plane ──────────────────────────────────────────────────────

  /**
   * Write a batch of co-located items (file/folder scope). General-scope
   * items go through the IndexService instead — they are silently ignored
   * here so callers can hand mixed batches.
   */
  public async writeCoLocatedItems(items: KnowledgeItem[], repoRoot: string): Promise<void> {
    const filesystem = new FileSystem(repoRoot)
    const byHost = new Map<string, KnowledgeItem[]>()

    for (const item of items) {
      if (item.scope.type === 'general') continue
      const list = byHost.get(item.writtenPath) ?? []
      list.push(item)
      byHost.set(item.writtenPath, list)
    }

    for (const [hostPath, hostItems] of byHost) {
      await this.appendCoLocated(filesystem, hostPath, hostItems, repoRoot)
    }
  }

  /**
   * Remove one co-located item from its hosting `KNOWLEDGE.md`. Used by the
   * validator. General-scope removal goes through IndexService.removeItem.
   */
  public async removeCoLocatedItem(item: KnowledgeItem, repoRoot: string): Promise<void> {
    if (item.scope.type === 'general') return
    const filesystem = new FileSystem(repoRoot)
    await this.rewriteCoLocatedExcluding(filesystem, item.writtenPath, item.title)
  }

  /**
   * Rebuild a co-located KNOWLEDGE.md from the given items currently assigned
   * to it. Used by the validator after multi-item removals.
   */
  public async rewriteCoLocatedFromItems(repoRoot: string, hostPath: string, items: KnowledgeItem[]): Promise<void> {
    const filesystem = new FileSystem(repoRoot)

    if (items.length === 0) {
      await this.unlinkIfExists(path.join(repoRoot, hostPath))
      return
    }

    const relativeDir = path.relative(repoRoot, path.dirname(path.join(repoRoot, hostPath))) || 'root'
    let content = `# Knowledge — ${relativeDir}\n\n${CO_LOCATED_HEADER}`

    for (const item of items) {
      content += SECTION_SEPARATOR
      content += this.formatCoLocatedSection(item)
    }

    await filesystem.writeFileWithDir(hostPath, content)
  }

  // ── Tree plane ─────────────────────────────────────────────────────────────

  /**
   * Render a leaf `.md` file containing the given items as topic-grouped
   * sections, with frontmatter for navigation. The IndexService computes the
   * leaf summary and keywords before calling this.
   */
  public async writeLeafFile(repoRoot: string, leaf: GraphNode, items: KnowledgeItem[]): Promise<void> {
    if (leaf.kind !== 'leaf') return

    const filesystem = new FileSystem(repoRoot)
    const content = this.formatLeafFile(leaf, items)
    await filesystem.writeFileWithDir(leaf.path, content)
  }

  /**
   * Render a branch's `_index.md` describing the folder and listing its
   * direct children with their summaries. Lets a navigating LLM agent pick
   * the next hop without reading any leaves.
   */
  public async writeBranchIndex(repoRoot: string, branch: GraphNode, children: GraphNode[]): Promise<void> {
    if (branch.kind !== 'branch') return

    const filesystem = new FileSystem(repoRoot)
    const indexPath = path.posix.join(branch.path, '_index.md')
    const content = this.formatBranchIndex(branch, children)
    await filesystem.writeFileWithDir(indexPath, content)
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  private async appendCoLocated(
    filesystem: FileSystem,
    hostPath: string,
    items: KnowledgeItem[],
    repoRoot: string,
  ): Promise<void> {
    const existing = (await filesystem.readFileOrNull(hostPath)) || ''
    const existingTitles = this.extractExistingTitles(existing)
    const newItems = items.filter((i) => !existingTitles.has(i.title))

    if (newItems.length === 0) {
      this.logger.log(`Skipping ${hostPath} — all items already present`)
      return
    }

    let content = existing
    if (!content) {
      const relativeDir = path.relative(repoRoot, path.dirname(path.join(repoRoot, hostPath))) || 'root'
      content = `# Knowledge — ${relativeDir}\n\n${CO_LOCATED_HEADER}`
    }

    for (const item of newItems) {
      content += SECTION_SEPARATOR
      content += this.formatCoLocatedSection(item)
    }

    await filesystem.writeFileWithDir(hostPath, content)
  }

  private async rewriteCoLocatedExcluding(
    filesystem: FileSystem,
    hostPath: string,
    excludeTitle: string,
  ): Promise<void> {
    const existing = await filesystem.readFileOrNull(hostPath)
    if (!existing) return

    const lines = existing.split('\n')
    const sections: { title: string; content: string }[] = []
    const head: string[] = []
    let currentSection: { title: string; content: string } | null = null

    for (const line of lines) {
      const headingMatch = /^## (.+)$/.exec(line)
      if (headingMatch) {
        if (currentSection) sections.push(currentSection)
        currentSection = { title: headingMatch[1], content: `${line}\n` }
      } else if (currentSection) {
        currentSection.content += `${line}\n`
      } else {
        head.push(line)
      }
    }

    if (currentSection) sections.push(currentSection)

    const kept = sections.filter((s) => s.title !== excludeTitle)

    if (kept.length === 0) {
      await this.unlinkIfExists(filesystem.resolve(hostPath))
      return
    }

    const body = kept.map((s) => s.content.replace(/\n---\n\s*$/, '').trimEnd()).join('\n\n---\n\n')
    const rebuilt = head.join('\n').trimEnd() + '\n\n' + body + '\n'
    await filesystem.writeFileWithDir(hostPath, rebuilt)
  }

  private formatCoLocatedSection(item: KnowledgeItem): string {
    const sourcesLine = item.sources.join(', ') || '—'

    let out = `\n## ${item.title}\n\n`
    out += `**Category:** ${KNOWLEDGE_CATEGORY_LABELS[item.category]}\n`
    out += `**Summary:** ${item.summary}\n`
    out += `**Sources:** ${sourcesLine}\n\n`
    out += `${item.content.trim()}\n`
    return out
  }

  private formatLeafFile(leaf: GraphNode, items: KnowledgeItem[]): string {
    const frontmatter = this.renderFrontmatter({
      id: leaf.id,
      title: this.toTitleCase(leaf.segment),
      summary: leaf.summary,
      keywords: leaf.keywords,
      parent: leaf.parentId ?? '',
      items: (leaf.itemIds ?? []).join(', '),
    })

    let out = `${frontmatter}\n# ${this.toTitleCase(leaf.segment)}\n\n`
    out += `> Auto-generated by 2context. ${items.length} finding${items.length === 1 ? '' : 's'} grouped by topic.\n\n`
    if (leaf.summary) {
      out += `${leaf.summary}\n\n`
    }

    for (const item of items) {
      out += `---\n\n`
      out += `## ${item.title}\n\n`
      out += `**Category:** ${KNOWLEDGE_CATEGORY_LABELS[item.category]}\n`
      out += `**Summary:** ${item.summary}\n`
      out += `**Sources:** ${item.sources.join(', ') || '—'}\n`
      if (item.relatedFiles.length > 0) {
        out += `**Related files:** ${item.relatedFiles.join(', ')}\n`
      }
      out += `\n${item.content.trim()}\n\n`
    }

    return out
  }

  private formatBranchIndex(branch: GraphNode, children: GraphNode[]): string {
    const frontmatter = this.renderFrontmatter({
      id: branch.id,
      title: this.toTitleCase(branch.segment),
      summary: branch.summary,
      keywords: branch.keywords,
      parent: branch.parentId ?? '',
      children: (branch.childIds ?? []).join(', '),
    })

    let out = `${frontmatter}\n# ${this.toTitleCase(branch.segment)}\n\n`
    if (branch.summary) {
      out += `${branch.summary}\n\n`
    }

    if (children.length === 0) {
      out += '_No knowledge items yet._\n'
      return out
    }

    out += `## Children\n\n`
    for (const child of children) {
      const filename = child.kind === 'leaf' ? `${child.segment}.md` : `${child.segment}/`
      const summary = child.summary || '_(no summary yet)_'
      out += `- **\`${filename}\`** — ${summary}\n`
    }
    out += '\n'
    return out
  }

  private renderFrontmatter(fields: Record<string, string | string[]>): string {
    const lines: string[] = ['---']
    for (const [key, value] of Object.entries(fields)) {
      if (Array.isArray(value)) {
        lines.push(`${key}: [${value.map((v) => JSON.stringify(v)).join(', ')}]`)
      } else {
        // Quote summaries that contain special characters or colons.
        const needsQuote = /[:#\n]/.test(value)
        lines.push(`${key}: ${needsQuote ? JSON.stringify(value) : value}`)
      }
    }
    lines.push('---')
    return lines.join('\n')
  }

  private toTitleCase(segment: string): string {
    return segment
      .split('-')
      .filter(Boolean)
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join(' ')
  }

  private extractExistingTitles(content: string): Set<string> {
    const titles = new Set<string>()
    const regex = /^## (.+)$/gm
    let match: RegExpExecArray | null

    while ((match = regex.exec(content)) !== null) {
      titles.add(match[1])
    }

    return titles
  }

  private async unlinkIfExists(absPath: string): Promise<void> {
    try {
      await fs.unlink(absPath)
    } catch {
      // Missing file is fine
    }
  }
}
